apiVersion: apps/v1
kind: Deployment
metadata:
  name: joomla
spec:
  replicas: 3
  selector:
    matchLabels:
      app: joomla
  template:
    metadata:
      labels:
        app: joomla
    spec:
      containers:
      - name: joomla
        image: joomla:latest
        env:
        - name: JOOMLA_DB_HOST
          value: mysql:3306
        - name: JOOMLA_DB_USER
          value: root
        - name: JOOMLA_DB_PASSWORD
          value: password
        - name: JOOMLA_DB_NAME
          value: joomla_db
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10
        volumeMounts:
        - name: joomla-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: joomla-persistent-storage
        persistentVolumeClaim:
          claimName: joomla-claim
