version: '3'

services:
  joomla:
    image: joomla:latest
    restart: always
    links:
      - joomladb:mysql
    depends_on:
      - joomladb
    ports:
      - 8080:80
    environment:
      JOOMLA_DB_HOST: joomladb:3306
      JOOMLA_DB_NAME: db_database
      JOOMLA_DB_USER: db_user
      JOOMLA_DB_PASSWORD: db_pass

  joomladb:
    image: mysql:5.6
    platform: linux/x86_64
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: db_root_pass
      MYSQL_DATABASE: db_database
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_pass
